name = "feedback-resonite-com"
main = "./src/backend/main.js"
compatibility_date = "2026-03-11"
compatibility_flags = [ "nodejs_compat" ]

[vars]
ENVIRONMENT = "production"

[assets]
directory = "./dist"
binding = "ASSETS"

[[analytics_engine_datasets]]
binding = "SCORE"
dataset = "SCORE"

[[d1_databases]]
binding = "DB"
database_name = "feedback-db"
database_id = "564f0061-df9e-4328-a746-f910c158da24"
migrations_dir = "../../migrations"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "a3e2dc40a0bd43c38615caec4b6e8ab9"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "feedback-resonite-files"

