name = "feedback-resonite-com"
main = "./src/backend/main.js"
compatibility_date = "2026-03-11"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[assets]
directory = "./dist"
binding = "ASSETS"

